### PR TITLE
Update from View.propTypes to ViewPropTypes to match RN v0.44.x

### PR DESCRIPTION
**Pull request by denis-shvets**
Update the ViewPropTypes to match the last revision of React Native V0.44.x

> View.propTypes to ViewPropTypes (53905a5) - @bvaughn
https://github.com/facebook/react-native/releases

### CODE REVIEW

**Comment by jshanson7** [comment]
Thanks @denis-shvets!

**Comment by Rovack** [comment]
@jshanson7 Is a version with this fix expected to be released soon?
Currently using this module with RN 0.44 throws warnings.

**Comment by Rovack** [comment]
@denis-shvets Same question?

**Comment by denis-shvets** [comment]
@Rovack If you need this library, best way to support own fork or find alternative. You can't depend on this one. Looks like @jshanson7 have no time to support it.

**Comment by jshanson7** [comment]
Sorry for the delay on this!  It's published.  @denis-shvets any interest in being a collaborator on this repo/npm package?

**Comment by denis-shvets** [comment]
@jshanson7 we can try, but usually I'm extremely busy to do something :-)

**Pull request merged**
