### PR TITLE
Version0.62

### PR DESCRIPTION
**Pull request by cedricboidin**
Remove warnings for react native 0.62

### CODE REVIEW

**Comment by weinixuehao** [comment]
Tried to clone with https://github.com/cedricboidin/react-native-swipeable.git#
9c18449 but failed to run project

**Comment by the-smart-home-maker** [comment]
When will this fix be merged?

**Comment by ademilter** [comment]
merge?

**Comment by weinixuehao** [comment]
The plugin is experience not good with [](https://github.com/Flipkart/recyclerlistview) and flatlist

**Comment by desaiparv5** [comment]
how to implement this in my project till this commit is merged?

**Review by matheushf — APPROVED** [review]

**Comment by Navipro70** [comment]
@cedricboidin Already approved. Please resolve conflicts and merge <3

**Comment by fgrgic** [comment]
Any updates on this?
It's a very nice library and would love to be able to use it without warnings

**Comment by Under-Warz** [comment]
Hi guys, any updates on this pr? thank's

**Comment by divyagoel-kiwi** [comment]
@denis-shvets I am new in react native and i want to install this library. Whenever I installed it install 0.6.0 version. How will I get this merged code

**Comment by denis-shvets** [comment]
> @denis-shvets I am new in react native and i want to install this library. Whenever I installed it install 0.6.0 version. How will I get this merged code

It depends on package version published on npm.
We can try to ping @jshanson7 to publish latest version.

**Comment by Geek-Jokey** [comment]
@jshanson7  to publish latest version. come on! go go go!  Thank you very much！

**Comment by y2kappa** [comment]
@jshanson7 can you publish the latest version please? Appreciate your work on this package.

**Comment by QuintonC** [comment]
-- removed.

**Comment by denis-shvets** [comment]
This also can be helpful - https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

**Comment by zienna** [comment]
@jshanson7 please publish the latest version

**Comment by ricardobeat** [comment]
@jshanson7 just ran into this at work. Maybe there is someone else who can handle the publishing chores for this?

**Comment by zoobibackups** [comment]
Does the warning removed???

**Pull request merged**
